"""
State models for the Bug Fix Expediter pipeline.

Defines the phase enum, data models for each pipeline stage,
and the complete BFEState TypedDict.
"""

from enum import Enum
from typing import Optional, TypedDict

from pydantic import BaseModel, Field


class BFEPhase( Enum ):
    """Phase machine for the Bug Fix Expediter pipeline."""
    # Active phases
    PACKAGING            = "packaging"
    DIAGNOSING           = "diagnosing"
    PROPOSING            = "proposing"
    FIXING               = "fixing"
    COMMITTING           = "committing"
    RETRYING             = "retrying"

    # Waiting phases
    WAITING_CONFIRMATION = "waiting_confirmation"

    # Terminal phases
    COMPLETED            = "completed"
    FAILED               = "failed"
    SKIPPED              = "skipped"


class DeadJobContext( BaseModel ):
    """
    Forensic context extracted from a dead (failed/interrupted) job.

    Requires:
        - id_hash, job_type, user_id, user_email, session_id, status, question_text are non-empty
        - status is "failed" or "interrupted"

    Ensures:
        - All fields populated from job_history table
        - stack_trace extracted from metadata_json if available
    """
    id_hash          : str
    job_type         : str
    user_id          : str
    user_email       : str
    session_id       : str
    status           : str                    # "failed" or "interrupted"
    question_text    : str
    error            : Optional[ str ]        = None
    stack_trace      : Optional[ str ]        = None
    routing_command  : Optional[ str ]        = None
    duration_seconds : Optional[ float ]      = None
    metadata_json    : Optional[ dict ]       = Field( default_factory=dict )
    created_at       : Optional[ str ]        = None
    started_at       : Optional[ str ]        = None
    completed_at     : Optional[ str ]        = None


class DiagnosisResult( BaseModel ):
    """
    Root cause analysis output from the diagnosis phase.

    Requires:
        - root_cause is non-empty
        - confidence is between 0.0 and 1.0

    Ensures:
        - Structured diagnosis for downstream proposal generation
    """
    root_cause          : str
    error_category      : str          # config, code_bug, dependency, timeout, resource, unknown
    confidence          : float = Field( ge=0.0, le=1.0 )
    evidence            : list[ str ]  = Field( default_factory=list )
    affected_components : list[ str ]  = Field( default_factory=list )
    is_transient        : bool         = False


class ProposedFix( BaseModel ):
    """
    A proposed fix generated by the propose phase.

    Requires:
        - title and description are non-empty
        - confidence is between 0.0 and 1.0

    Ensures:
        - Actionable fix proposal with risk assessment
    """
    title            : str
    description      : str
    fix_type         : str          # config_change, code_patch, retry, manual
    confidence       : float = Field( ge=0.0, le=1.0 )
    risk_level       : str          = "low"
    estimated_effort : str          = "minimal"
    changes          : list[ dict ] = Field( default_factory=list )


class FixResult( BaseModel ):
    """
    Outcome of applying a proposed fix.

    Ensures:
        - Clear success/failure signal for retry decision
        - Phase 5 git fields populated after run_git_strategy() completes
    """
    applied        : bool
    success        : bool
    details        : str            = ""
    retry_eligible : bool           = False
    # Phase 5 additions (populated after run_git_strategy)
    git_strategy   : Optional[ str ] = None   # "commit_only" | "branch_and_pr" | "branch_only" | None
    commit_hash    : Optional[ str ] = None
    branch_name    : Optional[ str ] = None
    pr_url         : Optional[ str ] = None


class BFEState( TypedDict ):
    """Complete state for a Bug Fix Expediter run."""
    # Input
    dead_job_id      : str
    extra_context    : str

    # Packaging Phase
    dead_job_context : Optional[ DeadJobContext ]

    # Diagnosis Phase
    diagnosis        : Optional[ DiagnosisResult ]

    # Proposal Phase
    proposed_fixes   : list[ ProposedFix ]
    selected_fix     : Optional[ ProposedFix ]
    user_approved    : bool

    # Fix Phase
    fix_result       : Optional[ FixResult ]

    # Retry Phase
    retry_job_id     : Optional[ str ]
    retry_status     : Optional[ str ]

    # Meta
    phase            : str
    error            : Optional[ str ]


def create_initial_state( dead_job_id: str, extra_context: str = "" ) -> BFEState:
    """
    Create initial BFEState for a new Bug Fix Expediter run.

    Requires:
        - dead_job_id is non-empty

    Ensures:
        - Returns BFEState with phase=PACKAGING and all fields initialized

    Args:
        dead_job_id: The id_hash of the dead job to fix
        extra_context: Optional user-provided context

    Returns:
        BFEState: Initial pipeline state
    """
    return BFEState(
        dead_job_id      = dead_job_id,
        extra_context    = extra_context,
        dead_job_context = None,
        diagnosis        = None,
        proposed_fixes   = [],
        selected_fix     = None,
        user_approved    = False,
        fix_result       = None,
        retry_job_id     = None,
        retry_status     = None,
        phase            = BFEPhase.PACKAGING.value,
        error            = None,
    )


def quick_smoke_test():
    """Quick smoke test for BFE state models."""
    import cosa.utils.util as cu

    cu.print_banner( "BFE State Models Smoke Test", prepend_nl=True )

    try:
        # 1: BFEPhase enum
        assert BFEPhase.PACKAGING.value == "packaging"
        assert BFEPhase.COMPLETED.value == "completed"
        assert BFEPhase.COMMITTING.value == "committing"
        assert len( BFEPhase ) == 10
        print( "✓ BFEPhase enum correct (10 values)" )

        # 2: DeadJobContext
        ctx = DeadJobContext(
            id_hash="dr-test::user1", job_type="deep_research",
            user_id="user1", user_email="t@t.com", session_id="s1",
            status="failed", question_text="test query", error="boom"
        )
        assert ctx.status == "failed"
        assert ctx.stack_trace is None
        print( "✓ DeadJobContext validates correctly" )

        # 3: DiagnosisResult
        diag = DiagnosisResult(
            root_cause="Missing config key", error_category="config", confidence=0.9
        )
        assert diag.is_transient == False
        print( "✓ DiagnosisResult validates correctly" )

        # 4: ProposedFix
        fix = ProposedFix(
            title="Add key", description="Add missing key to INI",
            fix_type="config_change", confidence=0.95
        )
        assert fix.risk_level == "low"
        print( "✓ ProposedFix validates correctly" )

        # 5: FixResult
        result = FixResult( applied=True, success=True, details="Key added" )
        assert result.retry_eligible == False
        assert result.git_strategy is None
        assert result.commit_hash is None
        assert result.branch_name is None
        assert result.pr_url is None
        # Phase 5 git fields accept values
        result_with_git = FixResult(
            applied=True, success=True, details="Key added",
            git_strategy="commit_only", commit_hash="abc1234"
        )
        assert result_with_git.git_strategy == "commit_only"
        assert result_with_git.commit_hash == "abc1234"
        print( "✓ FixResult validates correctly (+ Phase 5 git fields)" )

        # 6: create_initial_state
        state = create_initial_state( "dr-test::user1", "extra info" )
        assert state[ "dead_job_id" ] == "dr-test::user1"
        assert state[ "phase" ] == "packaging"
        assert state[ "diagnosis" ] is None
        print( "✓ create_initial_state works correctly" )

        print( "\n✓ BFE State Models smoke test completed successfully" )

    except Exception as e:
        print( f"\n✗ Smoke test failed: {e}" )
        import traceback
        traceback.print_exc()


if __name__ == "__main__":
    quick_smoke_test()
